# Generated by Django 5.1.4 on 2024-12-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
                ('start', models.DateField()),
                ('due', models.DateField(blank=True, null=True)),
                ('lang', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Ideation', 'Ideation'), ('Planned', 'Planned'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Refactoring', 'Refactoring'), ('Testing', 'Testing'), ('Deployed', 'Deployed'), ('Completed', 'Completed'), ('Archived', 'Archived'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
                ('img', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
